apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-web
  template:
    metadata:
      labels:
        app: tg-web
    spec:
      containers:
      - image: okteto/hello-world:node
        name: tg-web
---

apiVersion: v1
kind: Service
metadata:
  name: tg-web
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "tg-web"
    port: 3000
  selector:
    app: tg-web
